config/routes.rb
Rails.application.routes.draw do
  resources :replacement_orders do
    member do
      get 'review', action: :review
      get 'accept', action: :accept
      get 'reject', action: :reject
    end
  end

  get    'sessions/new'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/replacement_order.rb
require 'aasm'

# model
class ReplacementOrder < ApplicationRecord
  include AASM

  belongs_to :owner,    class_name: 'User'
  belongs_to :indicate, class_name: 'User'

  aasm column: 'state' do
    after_all_transitions :log_status_change

    state :init, initial: true
    state :awaiting_review
    state :being_reviewed
    state :awaiting_repair
    state :accepted
    state :rejected

    event :submit do
      transitions from: :init, to: :awaiting_review
    end

    event :review do
      transitions from: :awaiting_review, to: :being_reviewed
    end

    event :accept do
      transitions from: :being_reviewed, to: :accepted
    end

    event :reject do
      transitions from: :being_reviewed, to: :rejected
    end

    event :repair do
      transitions from: :being_reviewed, to: :awaiting_repair
    end

    event :repaired do
      transitions from: :awaiting_repair, to: :awaiting_review
    end
  end

  private

  def log_status_change
    puts "Changed from #{aasm.from_state}
      to #{aasm.to_state}
      (event: #{aasm.current_event})"
  end
end

app/models/user.rb
# User
class User < ApplicationRecord
  hash_owner = { class_name: 'ReplacementOrder', foreign_key: 'owner_id' }
  has_many :owner_replacement_order, hash_owner

  hash_idicate = { class_name: 'ReplacementOrder', foreign_key: 'indicate_id' }
  has_many :indicate_replacement_order, hash_idicate

  def authenticate(password)
    self.password == password
  end

  def admin?
    cargo == 'admin'
  end
end

app/controllers/application_controller.rb
# ApplicationController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authorize
    redirect_to root_url unless logged_in?
  end
end

app/controllers/replacement_orders_controller.rb
# ReplacementOrdersController
class ReplacementOrdersController < ApplicationController
  only = %i[show edit update destroy review accept reject]
  before_action :set_replacement_order, only: only
  before_action :authorize

  # GET /replacement_orders
  # GET /replacement_orders.json
  def index
    @replacement_orders = ReplacementOrder.order :end_date
  end

  # GET /replacement_orders/1
  # GET /replacement_orders/1.json
  def show; end

  # GET /replacement_orders/new
  def new
    @replacement_order = ReplacementOrder.new
  end

  def review
    @replacement_order.review!
    handler('Revisado com sucesso.')
  end

  def accept
    @replacement_order.accept!
    handler('Pedido Aceito.')
  end

  def reject
    @replacement_order.reject!
    handler('Pedido rejeitado.')
  end

  # GET /replacement_orders/1/edit
  def edit; end

  # POST /replacement_orders
  # POST /replacement_orders.json
  def create
    @replacement_order = ReplacementOrder.new(replacement_order_params)
    msg = 'Replacement order was successfully created.'

    respond_to do |format|
      if @replacement_order.submit!
        format.html { redirect_to replacement_orders_url, notice: msg }
      else
        format.html { render :new }
      end
    end
  end

  private

  def handler(msg)
    respond_to do |format|
      format.html { redirect_to replacement_orders_url, notice: msg }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_replacement_order
    @replacement_order = ReplacementOrder.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def replacement_order_params
    permissive = %i[start_date end_date comments owner_id
                    indicate_id comments_indicate]

    params.require(:replacement_order).permit(permissive)
  end
end

app/controllers/sessions_controller.rb
# Sessions
class SessionsController < ApplicationController
  before_action :block_access, except: %w[destroy create new]

  def new; end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)

    if @user && @user.authenticate(params[:session][:password])
      sign_in(@user)
      redirect_to replacement_orders_path
    else
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/replacement_orders_helper.rb
module ReplacementOrdersHelper
  def awaiting_review?(replacement_order)
    replacement_order.state == 'awaiting_review' 
  end

  def being_review?(replacement_order)
    replacement_order.state == 'being_reviewed'
  end
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
# SessionsHelper
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def admin?(user)
    user.cargo == 'admin'
  end

  def block_access
    current_user.present? if redirect_to replacement_orders_url
  end

  def logged_in?
    !current_user.nil?
  end

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav>
      <ul>
        <% if logged_in? %>
          <%= link_to "Log out", sign_out_path, method: "delete" %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStateMachine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/replacement_orders/_form.html.erb
<%= form_with(model: replacement_order, local: true) do |form| %>
  <% if replacement_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(replacement_order.errors.count, "error") %> prohibited this replacement_order from being saved:</h2>

      <% replacement_order.errors.each do |message| %>
        <p class="alert alert-danger"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <div class="border p-3 mb-2">
    <div class="form-group row">
      <%= form.label :Substituido, class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-4">
        <%= form.collection_select :owner_id, User.all, :id, :name %>
      </div>
    </div>

<!--    <div class="form-group row">
      <%= form.label 'Cargo/ função que o indicado terá que exercer', class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-4 ">
        <%= form.text_field :cargo, id: :replacement_order_cargo, class: 'form-control' %>
      </div>
    </div>
-->
    <div class="form-group row">
      <%= form.label 'Periodo da substitução, de:', class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9 col-md-4" >
        <%= form.date_field :start_date, id: :replacement_order_start_date, class: 'form-control', min: Date.today %>
      </div>
    </div>
    <div class="form-group row">
      <%= form.label :ate, class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9 col-md-4" >
        <%= form.date_field :end_date, id: :replacement_order_end_date, class: 'form-control', min: Date.today %>
      </div>
    </div>
    <div class="form-group row">
      <%= form.label :total_de_dias, class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-2">
        <%= form.text_field :dias, id: :diff_day, class: 'form-control', disabled: 'disabled' %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :observaçôes, class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9">
        <%= form.text_area :comments, id: :replacement_order_comments, class: 'form-control', rows: 3 %>
      </div>
    </div>
  </div>

  <fieldset class="border p-3">
    <div class="form-group row">
      <%= form.label :Indicado, class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9">
        <%= form.collection_select :indicate_id, User.all, :id, :name %>
      </div>
    </div>

    <div class="form-group row">
      <%= form.label :observaçôes, class: 'col-sm-3 col-form-label' %>
      <div class="col-sm-9">
        <%= form.text_area :comments_indicate, id: :replacement_order_comments_indicate, class: 'form-control', rows: 2 %>
      </div>
    </div>

    <div class="float-right">
      <%= link_to 'Cancelar', replacement_orders_path , class: 'btn' %>
      <%= form.submit "Solicitar", class: 'btn btn-primary' %>
    </div>
  </fieldset>

<% end %>

app/views/replacement_orders/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comments:</strong>
  <%= @replacement_order.comments %>
</p>

<p>
  <strong>User:</strong>
  <%= @replacement_order.owner.name %>
</p>

<p>
  <strong>Indicate:</strong>
  <%= @replacement_order.indicate.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @replacement_order.start_date.strftime("%d-%m-%Y") %>
</p>

<p>
  <strong>End date:</strong>
  <%= @replacement_order.end_date.strftime("%d-%m-%Y")  %>
</p>

<p>
  <strong>Comments for Indicate</strong>
  <%= @replacement_order.comments_indicate %>
</p>

<p>
  <strong>State</strong>
  <%= @replacement_order.state %>
</p>

<%= link_to 'Back', replacement_orders_path %>

<% if @replacement_order.state == 'being_reviewed' %>
  <%= link_to 'Aceitar', "/replacement_orders/#{@replacement_order.id}/accept", data: { confirm: 'Foi aceito ?' } %>
  <%= link_to 'Rejeitar', "/replacement_orders/#{@replacement_order.id}/reject", data: { confirm: 'Foi rejeitado ?' } %>
<% elsif @replacement_order.state == 'awaiting_review' %>
  <%= link_to 'Revisar', "/replacement_orders/#{@replacement_order.id}/review", data: { confirm: 'Revisão terminada ?' } %>
<% end %>

app/views/replacement_orders/edit.html.erb
<h1>Editing Replacement Order</h1>
<%= render 'form', replacement_order: @replacement_order %>

<%= link_to 'Show', @replacement_order %> |
<%= link_to 'Back', replacement_orders_path %>

app/views/replacement_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Replacement Orders</h1>

<table class="table">
  <thead>
    <tr>
      <th>Owner</th>
      <th>Status</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Indicate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replacement_orders.each do |replacement_order| %>
      <tr>
        <td><%= replacement_order.owner.name%></td>
        <td><%= replacement_order.state%></td>
        <td><%= replacement_order.start_date.strftime("%d-%m-%Y") %></td>
        <td><%= replacement_order.end_date.strftime("%d-%m-%Y") %></td>
        <td><%= replacement_order.indicate.name%></td>
        <% if awaiting_review? replacement_order and @current_user.admin? %>
          <td>
            <%= link_to 'Abilitar Revisão', 
              "/replacement_orders/#{replacement_order.id}/review", data: { confirm: 'Abilitar Revisâo?' } %>
          </td>
        <% elsif being_review? replacement_order and @current_user.admin? %>
          <td><%= link_to 'Finalizar', replacement_order %></td>
        <% elsif ['accepted', 'rejected'].include? replacement_order.state %>
          <td>Finalizado</td>
        <% end %>
        <!-- <td><%= link_to 'Destroy', replacement_order, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Pedido', new_replacement_order_path %>

app/views/replacement_orders/new.html.erb
<h1>Formulario para solicitação</h1>

<ul class="nav nav-tabs" id="" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">
      Solicitação
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= 'disabled' if @replacement_order.state == 'init' %>" 
      id="valid-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">
      Validação
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= 'disabled' if @replacement_order.state == 'init' %>" 
      id="final-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">
      Final
    </a>
  </li>
</ul>

<div class="tab-content" id="">
  <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
    <%= render 'form', replacement_order: @replacement_order %>
  </div>
    <div class="tab-pane fade" id="valid" role="tabpanel" aria-labelledby="profile-tab">
    <% unless @replacement_order.owner.nil? %>
      <%= render 'show', replacement_order: @replacement_order %>
    <% end %>
  </div>
  <div class="tab-pane fade" id="final" role="tabpanel" aria-labelledby="contact-tab">
  </div>
</div>

app/views/replacement_orders/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Cadidate:</strong>
  <%= @replacement_order.owner.name %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @replacement_order.comments %>
</p>

<p>
  <strong>Indicate:</strong>
  <%= @replacement_order.indicate.name %>
</p>

<p>
  <strong>Comments for Indicate</strong>
  <%= @replacement_order.comments_indicate %>
</p>

<p>
  <strong>State</strong>
  <%= @replacement_order.state %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @replacement_order.start_date.strftime("%d-%m-%Y") %>
</p>

<p>
  <strong>End date:</strong>
  <%= @replacement_order.end_date.strftime("%d-%m-%Y")  %>
</p>



<%= link_to 'Back', replacement_orders_path %>

<% if @replacement_order.state == 'being_reviewed' %>
  <%= link_to 'Aceitar', "/replacement_orders/#{@replacement_order.id}/accept", data: { confirm: 'Foi aceito ?' } %>
  <%= link_to 'Rejeitar', "/replacement_orders/#{@replacement_order.id}/reject", data: { confirm: 'Foi rejeitado ?' } %>
<% end %>